# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageLoad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimages',
            name='title',
            field=models.CharField(default='New Pic', max_length=65),
        ),
    ]
