# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageLoad', '0002_myimages_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimages',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
